version: 2.1

orbs:
    docker: circleci/docker@1.0.1
jobs:
    build:
        docker:
            - image: node:current-alpine
        steps:
            - run:
                  name: Build
                  command: echo $CIRCLE_BUILD_NUM
    deploy-dev:
        machine:
            image: ubuntu-1604:202004-01
        steps:
            - run:
                  name: Version Number
                  command: echo $(cat version.txt)
    deploy-qa:
        machine:
            image: ubuntu-1604:202004-01
        steps:
            - run:
                  name: Version Number
                  command: echo $(cat version.txt)
    deploy-prod:
        machine:
            image: ubuntu-1604:202004-01
        steps:
            - run:
                  name: Version Number
                  command: echo $(cat version.txt)
workflows:
    version: 2
    workfow:
        jobs:
            - build
            - deploy-dev:
                requires:
                  - build
            - deploy-qa:
                  requires:
                      - deploy-dev
            - deploy-prod:
                  requires:
                      - deploy-qa
